headersOrigin = "config"
redirectsOrigin = "config"

[functions]

[functions."*"]

[[plugins]]
origin = "default"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "C:\\Users\\Phant\\OneDrive\\Desktop\\sopmaster.tech.2\\.next"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build && cp public/_redirects .next/_redirects"

[build.environment]
SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_APP_URL"

[build.processing]
skip_processing = false

[build.processing.css]
bundle = true
minify = true

[build.processing.html]
pretty_urls = true

[build.processing.images]
compress = true

[build.processing.js]
bundle = true
minify = true

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
from = "/api/*"
to = "/api/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]