"use client";

import { useState, useEffect } from "react";
import { useStore } from "@/lib/store";
import { generateBatchPackage } from "@/lib/batch-sop-generator";
import { JURISDICTION_REGULATORY, buildSopHtml } from "@/lib/utils";
import { useRouter } from "next/navigation";
import type { Industry, BusinessModel, Department, Jurisdiction, BatchSOP } from "@/types";

const BATCH_FUNCTION_URL = "/api/generate/batch";

const ALL_DEPARTMENTS: Department[] = [
  "Executive Management", "Operations", "Sales", "Marketing", "Customer Support",
  "Finance", "Human Resources", "Information Technology", "Procurement", "Compliance",
  "Logistics", "Administration", "Training & Development", "E-Commerce", "Management / Governance",
];

const ALL_INDUSTRIES: { value: Industry; label: string }[] = [
  { value: "SaaS", label: "SaaS / Technology" }, { value: "Construction", label: "Construction" },
  { value: "Accountancy", label: "Accountancy" }, { value: "E-Commerce", label: "E-Commerce" },
  { value: "Healthcare", label: "Healthcare" }, { value: "ProfessionalServices", label: "Professional Services" },
  { value: "Manufacturing", label: "Manufacturing" }, { value: "Logistics", label: "Logistics" },
  { value: "Finance", label: "Finance & Banking" }, { value: "Education", label: "Education" },
  { value: "Hospitality", label: "Hospitality" }, { value: "RealEstate", label: "Real Estate" },
];

const ALL_MODELS: { value: BusinessModel; label: string }[] = [
  { value: "SaaS", label: "SaaS" }, { value: "E-Commerce", label: "E-Commerce" },
  { value: "ProfessionalServices", label: "Professional Services" }, { value: "Construction", label: "Construction" },
  { value: "Manufacturing", label: "Manufacturing" }, { value: "Retail", label: "Retail" },
  { value: "Healthcare", label: "Healthcare" }, { value: "Education", label: "Education" },
];

function downloadPackage(sops: BatchSOP[], companyName: string) {
  function escapeHtml(s: string): string {
    return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
  }

  const bodiesHtml = sops.map(s => {
    const sectionsHtml = s.content.map(sec => {
      const linesHtml = sec.content.map(line => {
        const trimmed = line.trim();
        if (/^Step \d+/.test(trimmed)) return `<p class="step-heading">${escapeHtml(trimmed)}</p>`;
        if (/^WHY:/.test(trimmed)) return `<p class="step-why">${escapeHtml(trimmed)}</p>`;
        if (/^HOW TO VERIFY:/.test(trimmed)) return `<p class="step-how">${escapeHtml(trimmed)}</p>`;
        if (/^(REAL.WORLD EXAMPLE|EXAMPLE):/i.test(trimmed)) return `<p class="step-example">${escapeHtml(trimmed)}</p>`;
        if (trimmed.startsWith("\u2610")) return `<p class="checklist-item">${escapeHtml(trimmed)}</p>`;
        if (trimmed.startsWith("\u2022") || trimmed.startsWith("* ")) return `<p class="bullet-item">${escapeHtml(trimmed)}</p>`;
        return `<p class="body-text">${escapeHtml(trimmed)}</p>`;
      }).join("\n");
      return `<div class="section">
        <h2 class="section-heading">${escapeHtml(sec.heading)}</h2>
        <div class="section-body">${linesHtml}</div>
      </div>`;
    }).join("\n");
    return `<div style="page-break-after:always;margin-bottom:24pt">
      <div class="doc-header">
        <div class="classification">Operational Document</div>
        <h1>${escapeHtml(s.title)}</h1>
        <p class="subtitle">${escapeHtml(companyName)} &mdash; ${escapeHtml(s.department)}</p>
      </div>
      <table class="meta-table">
        <tr>
          <td class="label-cell">Document ID</td>
          <td class="value-cell">${escapeHtml(s.id)}</td>
          <td class="label-cell">Department</td>
          <td class="value-cell">${escapeHtml(s.department)}</td>
        </tr>
        <tr>
          <td class="label-cell">Company</td>
          <td class="value-cell">${escapeHtml(companyName)}</td>
          <td class="label-cell">Industry</td>
          <td class="value-cell">${escapeHtml(s.industry)}</td>
        </tr>
      </table>
      ${sectionsHtml}
      <div class="footer">
        <p><strong>${escapeHtml(companyName)}</strong> &mdash; Standard Operating Procedure</p>
        <p>Generated by SOPMaster &mdash; Confidential &mdash; Not for external distribution without authorisation.</p>
      </div>
    </div>`;
  }).join("");
  const html = `<!DOCTYPE html>
<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
<head><meta charset="utf-8"><title>Batch SOP Package - ${escapeHtml(companyName)}</title>
<style>
  @page { margin: 1in 0.75in; }
  body { font-family:'Calibri','Arial',sans-serif; color:#222; line-height:1.45; font-size:11pt; max-width:7.2in; margin:0 auto; padding:0; }
  .doc-header { text-align:center; margin-bottom:24pt; padding-bottom:12pt; border-bottom:3px solid #1a1a2e; }
  .doc-header .classification { display:inline-block; font-size:9pt; font-weight:700; color:#fff; background:#1a1a2e; padding:3pt 12pt; margin-bottom:8pt; text-transform:uppercase; letter-spacing:2pt; }
  .doc-header h1 { font-size:22pt; font-weight:700; color:#1a1a2e; margin:0 0 4pt 0; text-transform:uppercase; letter-spacing:1pt; }
  .doc-header .subtitle { font-size:11pt; color:#555; margin:4pt 0; }
  .meta-table { width:100%; border-collapse:collapse; margin:12pt 0 18pt 0; }
  .meta-table td { padding:5pt 8pt; font-size:10pt; border:1px solid #ccc; vertical-align:top; }
  .meta-table td.label-cell { font-weight:600; color:#1a1a2e; width:22%; background:#f5f5f5; }
  .meta-table td.value-cell { color:#333; }
  .section { margin-bottom:16pt; }
  .section-heading { font-size:13pt; font-weight:700; color:#1a1a2e; margin:0 0 6pt 0; padding-bottom:4pt; border-bottom:2px solid #1a1a2e; }
  .section-body { margin-top:6pt; }
  .body-text { font-size:11pt; line-height:1.5; margin:2pt 0 6pt 0; color:#333; }
  .step-heading { font-size:11pt; line-height:1.5; margin:8pt 0 2pt 0; color:#1a1a2e; font-weight:600; }
  .step-why { font-size:10pt; line-height:1.4; margin:0 0 1pt 18pt; color:#555; font-style:italic; }
  .step-how { font-size:10pt; line-height:1.4; margin:0 0 4pt 18pt; color:#666; }
  .step-example { font-size:10pt; line-height:1.4; margin:0 0 8pt 18pt; color:#444; }
  .bullet-item { font-size:11pt; line-height:1.45; margin:1pt 0; color:#333; }
  .checklist-item { font-size:11pt; line-height:1.45; margin:1pt 0; color:#333; }
  .footer { font-size:9pt; color:#888; margin-top:24pt; padding-top:8pt; border-top:1px solid #ccc; text-align:center; }
  .footer p { margin:1pt 0; }
</style></head>
<body>${bodiesHtml}</body></html>`;
  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = window.document.createElement("a");
  a.href = url; a.download = `SOP_Batch_${companyName.replace(/[^a-zA-Z0-9]/g, "_")}_${new Date().toISOString().slice(0, 10)}.html`; a.click();
  URL.revokeObjectURL(url);
}

export default function BatchPage() {
  const session = useStore((s) => s.session);
  const getCompany = useStore((s) => s.getCompany);
  const deductCredit = useStore((s) => s.deductCredit);
  const addNotification = useStore((s) => s.addNotification);
  const companyProfile = useStore((s) => s.companyProfile);
  const router = useRouter();
  const company = getCompany();

  const [companyName, setCompanyName] = useState(company?.name || "");
  const [industry, setIndustry] = useState<Industry>((companyProfile?.industry as Industry) || "ProfessionalServices");
  const [jurisdiction, setJurisdiction] = useState<string>(company?.jurisdiction || "UK");
  const [companySize, setCompanySize] = useState(companyProfile?.companySize || "10");
  const [businessModel, setBusinessModel] = useState<BusinessModel>("ProfessionalServices");
  const [softwareInput, setSoftwareInput] = useState("");
  const [softwareStack, setSoftwareStack] = useState<string[]>(companyProfile?.softwareStack || []);
  const [businessGoals, setBusinessGoals] = useState(companyProfile?.businessGoals || "");
  const [operationalChallenges, setOperationalChallenges] = useState(companyProfile?.operationalChallenges || "");
  const [selectedDepartments, setSelectedDepartments] = useState<Department[]>(companyProfile?.departments || []);
  const [generating, setGenerating] = useState(false);
  const [logs, setLogs] = useState<string[]>([]);
  const [result, setResult] = useState<{ sops: BatchSOP[]; totalCount: number; departmentCounts: Record<string, number> } | null>(null);
  const [progress, setProgress] = useState(0);
  const [error, setError] = useState("");

  useEffect(() => {
    if (company) { setCompanyName(company.name); setJurisdiction(company.jurisdiction); }
    if (companyProfile?.industry) setIndustry(companyProfile.industry as Industry);
    if (companyProfile?.companySize) setCompanySize(companyProfile.companySize);
    if (companyProfile?.departments && companyProfile.departments.length > 0) setSelectedDepartments(companyProfile.departments);
    if (companyProfile?.softwareStack) setSoftwareStack(companyProfile.softwareStack);
  }, [company, companyProfile]);

  const toggleDept = (d: Department) => { setSelectedDepartments(prev => prev.includes(d) ? prev.filter(x => x !== d) : [...prev, d]); };
  const addSoftware = (s: string) => { if (s.trim() && !softwareStack.includes(s.trim())) setSoftwareStack([...softwareStack, s.trim()]); setSoftwareInput(""); };
  const removeSoftware = (s: string) => setSoftwareStack(softwareStack.filter(x => x !== s));

  const handleGenerate = async () => {
    setError("");
    if (!companyName.trim() || selectedDepartments.length === 0) { setError("Company name and at least one department are required."); return; }
    if (!company?.subscriptionActive && !session?.isDirector) { setError("Batch generation requires an active subscription. Subscribe in Administration."); return; }
    const batchCost = selectedDepartments.length * 30;
    if (!session?.isDirector) {
      const comp = getCompany();
      if (!comp || comp.credits < batchCost) { setError(`Insufficient credits. Batch requires ${batchCost} credits (30 per department).`); return; }
    }
    setGenerating(true); setProgress(0); setLogs([]); setResult(null);

    const BATCH_MS = selectedDepartments.length <= 7 ? 24000 : 40000;
    const LOG_INTERVAL_MS = selectedDepartments.length <= 7 ? 4000 : 6000;
    const loadingLogs = ["Preparing company profile...", "Loading department libraries...", `Mapping ${selectedDepartments.length} departments...`, `Applying ${industry} industry context...`, "Building documentation packages...", "Performing quality review...", "Formatting outputs..."];
    const startedAt = Date.now();
    let logIdx = 0;

    let batchResult: any;

    const tick = () => {
      const elapsed = Date.now() - startedAt;
      const pct = Math.min(95, Math.round((elapsed / BATCH_MS) * 95));
      setProgress(pct);
      if (logIdx < loadingLogs.length) { setLogs(l => [...l, loadingLogs[logIdx]]); logIdx++; }
    };
    tick();
    const interval = setInterval(tick, LOG_INTERVAL_MS);

    try {
      const res = await fetch(BATCH_FUNCTION_URL, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          companyName: companyName.trim(),
          industry, jurisdiction, companySize, businessModel,
          softwareStack: softwareStack.length > 0 ? softwareStack : ["internal system"],
          departments: selectedDepartments, format: "json",
        }),
      });
      if (res.ok) {
        const data = await res.json();
        batchResult = data;
      } else {
        throw new Error("remote fail");
      }
    } catch {
      const batchInput = { companyName: companyName.trim(), industry, companySize, businessModel, softwareStack: softwareStack.length > 0 ? softwareStack : ["internal system"], businessGoals, operationalChallenges, departments: selectedDepartments };
      batchResult = generateBatchPackage(batchInput);
    }

    const elapsed = Date.now() - startedAt;
    const remaining = BATCH_MS - elapsed;
    if (remaining > 0) {
      await new Promise((r) => setTimeout(r, remaining));
    }

    clearInterval(interval);
    setProgress(100);
    await deductCredit(batchCost);
    setResult(batchResult);
    setLogs(l => [...l, `Package complete: ${batchResult.totalCount} SOPs across ${selectedDepartments.length} departments`]);
    setGenerating(false);
    addNotification({ type: "sop_generated", title: "Batch SOPs Generated", message: `${batchResult.totalCount} SOPs generated across ${selectedDepartments.length} departments for ${industry}.` });
  };

  if (!session || !company) return null;

  const jurisdictionInfo = JURISDICTION_REGULATORY[jurisdiction];
  const isHalfPackage = selectedDepartments.length <= 7;

  return (
    <div style={{ maxWidth: "1120px", margin: "0 auto", padding: "32px 24px" }} className="fade-in">
      <div style={{ marginBottom: "24px" }}>
        <h1 style={{ fontSize: "20px", fontWeight: 600, color: "#F1F5F9", marginBottom: "4px" }}>
          Batch Generation
        </h1>
        <p style={{ fontSize: "13px", color: "#64748B" }}>
          Generate a complete operational documentation package across multiple departments. Industry and jurisdiction-specific. {isHalfPackage ? "Half package" : "Full package"}.
        </p>
      </div>

      {!company.subscriptionActive && !session?.isDirector && (
        <div className="card" style={{ marginBottom: "20px", padding: "16px 20px", borderColor: "#F59E0B" }}>
          <p style={{ fontSize: "13px", color: "#F59E0B", fontWeight: 500 }}>Subscription required</p>
          <p style={{ fontSize: "12px", color: "#94A3B8", marginTop: "4px" }}>Batch generation requires an active subscription. Go to Administration to subscribe.</p>
        </div>
      )}

      {error && <div className="card" style={{ marginBottom: "16px", padding: "12px 16px", borderColor: "#EF4444" }}><p style={{ fontSize: "13px", color: "#EF4444" }}>{error}</p></div>}

      {!result ? (
        <div style={{ position: "relative" }}>
          {!company.subscriptionActive && !session?.isDirector && (
            <div style={{
              position: "absolute", inset: 0, background: "rgba(15,23,42,0.85)", zIndex: 20,
              display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center",
              borderRadius: "8px", minHeight: "500px",
            }}>
              <div className="card" style={{ maxWidth: "400px", textAlign: "center", borderColor: "#F59E0B" }}>
                <p style={{ fontSize: "15px", fontWeight: 600, color: "#F59E0B", marginBottom: "8px" }}>Subscription Required</p>
                <p style={{ fontSize: "13px", color: "#94A3B8", marginBottom: "16px", lineHeight: 1.5 }}>
                  Batch Generation requires an active subscription. Subscribe in Administration to unlock this feature.
                </p>
                <button onClick={() => router.push("/settings")} className="btn btn-primary" style={{ padding: "8px 20px" }}>
                  Go to Administration
                </button>
              </div>
            </div>
          )}
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "20px" }}>
          <div className="card">
            <div className="card-header">Organisation</div>
            <div style={{ marginBottom: "16px" }}>
              <label>Company</label>
              <input type="text" value={companyName} onChange={e => setCompanyName(e.target.value)} placeholder="Company name" />
            </div>
            <div style={{ marginBottom: "16px" }}>
              <label>Industry</label>
              <select value={industry} onChange={e => setIndustry(e.target.value as Industry)}>
                {ALL_INDUSTRIES.map(i => <option key={i.value} value={i.value}>{i.label}</option>)}
              </select>
            </div>
            <div style={{ marginBottom: "16px" }}>
              <label>Jurisdiction</label>
              <select value={jurisdiction} onChange={e => setJurisdiction(e.target.value)}>
                {Object.entries(JURISDICTION_REGULATORY).map(([key, val]) => <option key={key} value={key}>{val.name}</option>)}
              </select>
            </div>
            <div>
              <label>Business Model</label>
              <select value={businessModel} onChange={e => setBusinessModel(e.target.value as BusinessModel)}>
                {ALL_MODELS.map(m => <option key={m.value} value={m.value}>{m.label}</option>)}
              </select>
            </div>
          </div>

          <div className="card">
            <div className="card-header">Operations</div>
            <div style={{ marginBottom: "16px" }}>
              <label>Company Size (employees)</label>
              <input type="number" value={companySize} onChange={e => setCompanySize(e.target.value)} placeholder="e.g., 25" />
            </div>
            <div style={{ marginBottom: "16px" }}>
              <label>Software Stack</label>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "4px", marginBottom: "8px" }}>
                {softwareStack.map(s => (
                  <span key={s} className="tag tag-blue" style={{ cursor: "pointer" }} onClick={() => removeSoftware(s)}>
                    {s} &times;
                  </span>
                ))}
              </div>
              <input type="text" value={softwareInput} onChange={e => setSoftwareInput(e.target.value)}
                onKeyDown={e => { if (e.key === "Enter") addSoftware(softwareInput); }} placeholder="Type and press Enter" />
            </div>
            <div style={{ marginBottom: "16px" }}>
              <label>Business Goals</label>
              <textarea value={businessGoals} onChange={e => setBusinessGoals(e.target.value)} placeholder="e.g., Scale operations, improve compliance" style={{ minHeight: "48px" }} />
            </div>
            <div>
              <label>Operational Challenges</label>
              <textarea value={operationalChallenges} onChange={e => setOperationalChallenges(e.target.value)} placeholder="e.g., Inconsistent processes, compliance gaps" style={{ minHeight: "48px" }} />
            </div>
          </div>

          <div style={{ gridColumn: "1 / -1" }}>
            <div className="card">
              <div className="card-header">Departments</div>
              <p style={{ fontSize: "12px", color: "#64748B", marginBottom: "12px" }}>Select departments to include in this batch generation.</p>
              <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))", gap: "4px" }}>
                {ALL_DEPARTMENTS.map(d => (
                  <button key={d} onClick={() => toggleDept(d)}
                    style={{
                      textAlign: "left", padding: "8px 12px", fontSize: "13px", borderRadius: "6px", cursor: "pointer",
                      background: selectedDepartments.includes(d) ? "rgba(59,130,246,0.08)" : "transparent",
                      border: selectedDepartments.includes(d) ? "1px solid rgba(59,130,246,0.3)" : "1px solid #334155",
                      color: selectedDepartments.includes(d) ? "#F1F5F9" : "#94A3B8",
                      transition: "all 0.1s ease",
                    }}>
                    {d}
                  </button>
                ))}
              </div>
              <div style={{ display: "flex", justifyContent: "space-between", marginTop: "8px" }}>
                <p style={{ fontSize: "12px", color: "#64748B" }}>{selectedDepartments.length} selected</p>
                <p style={{ fontSize: "12px", color: "#64748B" }}>
                  Est. {isHalfPackage ? "3 minutes" : "5 minutes"}
                </p>
              </div>
            </div>
          </div>

          <div style={{ gridColumn: "1 / -1" }}>
            <div style={{ marginBottom: "12px" }}>
              <span style={{ fontSize: "12px", color: "#64748B" }}>
                {session?.isDirector ? "Director override" : `${company.credits} credits available · ${selectedDepartments.length * 30} required (30/dept)`}
              </span>
            </div>
            <button onClick={handleGenerate} disabled={generating || !companyName.trim() || selectedDepartments.length === 0}
              className="btn btn-primary" style={{ width: "100%", padding: "10px 20px", fontSize: "14px" }}>
              {generating ? "Generating..." : `Generate ${industry} Package \u2014 ${selectedDepartments.length} Departments`}
            </button>
          </div>
        </div>
      </div>
      ) : generating ? (
        <div className="card" style={{ maxWidth: "480px", margin: "0 auto", textAlign: "center", padding: "48px 32px" }}>
          <h2 style={{ fontSize: "18px", fontWeight: 600, color: "#F1F5F9", marginBottom: "4px" }}>Generating Package</h2>
          <p style={{ fontSize: "13px", color: "#64748B", marginBottom: "20px" }}>~{selectedDepartments.length * 30} seconds</p>
          <div className="progress-bar" style={{ marginBottom: "8px" }}>
            <div className="progress-fill" style={{ width: `${progress}%` }} />
          </div>
          <p style={{ fontSize: "12px", color: "#64748B", marginBottom: "16px" }}>{Math.round(progress)}%</p>
          <div style={{ textAlign: "left", padding: "12px 16px", background: "rgba(0,0,0,0.2)", borderRadius: "6px", maxHeight: "160px", overflowY: "auto" }}>
            {logs.map((log, i) => (
              <p key={i} style={{ fontSize: "12px", color: "#94A3B8", marginBottom: "4px", fontFamily: "monospace" }}>{log}</p>
            ))}
          </div>
        </div>
      ) : (
        <div className="fade-in">
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "16px" }}>
            <span style={{ fontSize: "13px", color: "#22C55E" }}>{result.totalCount} SOPs generated for {industry}</span>
            <div style={{ display: "flex", gap: "8px" }}>
              <button onClick={() => downloadPackage(result.sops, companyName)} className="btn btn-secondary" style={{ fontSize: "12px" }}>
                Download Package (HTML)
              </button>
              <button onClick={() => { setResult(null); setLogs([]); setProgress(0); }} className="btn btn-primary" style={{ fontSize: "12px" }}>
                New Batch
              </button>
            </div>
          </div>

          <div className="card mobile-safe-overflow" style={{ padding: 0 }}>
            <div className="batch-results-grid" style={{ gap: "0" }}>
              <div style={{ padding: "16px", borderRight: "1px solid #334155", borderBottom: "1px solid #334155" }}>
                <div className="stat-label">Total SOPs</div>
                <div className="stat-value">{result.totalCount}</div>
              </div>
              <div style={{ padding: "16px", borderRight: "1px solid #334155", borderBottom: "1px solid #334155" }}>
                <div className="stat-label">Departments</div>
                <div className="stat-value">{selectedDepartments.length}</div>
              </div>
              <div style={{ padding: "16px", borderRight: "1px solid #334155", borderBottom: "1px solid #334155" }}>
                <div className="stat-label">Industry</div>
                <div className="stat-value" style={{ fontSize: "16px" }}>{industry}</div>
              </div>
              <div style={{ padding: "16px", borderBottom: "1px solid #334155" }}>
                <div className="stat-label">Company</div>
                <div className="stat-value" style={{ fontSize: "16px" }}>{companyName}</div>
              </div>
            </div>
          </div>

          {Object.entries(result.departmentCounts).map(([dept, count]) => (
            <div className="card mobile-safe-overflow" key={dept} style={{ marginTop: "12px", padding: 0 }}>
              <div style={{ padding: "10px 16px", borderBottom: "1px solid #334155" }}>
                <span style={{ fontSize: "12px", fontWeight: 600, color: "#F1F5F9", textTransform: "uppercase", letterSpacing: "0.04em" }}>{dept}</span>
                <span style={{ fontSize: "12px", color: "#64748B", marginLeft: "8px" }}>{count} SOPs</span>
              </div>
              {result.sops.filter(s => s.department === dept).map((sop, idx) => (
                <div key={sop.id} className="doc-row">
                  <span style={{ color: "#F1F5F9", fontWeight: 500, flex: 1 }}>{idx + 1}. {sop.title}</span>
                  <span style={{ fontSize: "11px", color: "#64748B", fontFamily: "monospace" }}>{sop.id}</span>
                  <span className="tag tag-green">Complete</span>
                </div>
              ))}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
