"use client";

import { useState, useEffect } from "react";
import { useStore } from "@/lib/store";
import { api } from "@/lib/api/client";
import { generateBatchPackage } from "@/lib/batch-sop-generator";
import { JURISDICTION_REGULATORY, buildSopHtml } from "@/lib/utils";
import { useRouter } from "next/navigation";
import type { Industry, BusinessModel, Department, Jurisdiction, BatchSOP } from "@/types";

const ALL_DEPARTMENTS: Department[] = [
  "Executive Management", "Operations", "Sales", "Marketing", "Customer Support",
  "Finance", "Human Resources", "Information Technology", "Procurement", "Compliance",
  "Logistics", "Administration", "Training & Development", "E-Commerce", "Management / Governance",
];

const ALL_INDUSTRIES: { value: Industry; label: string }[] = [
  { value: "SaaS", label: "SaaS / Technology" }, { value: "Construction", label: "Construction" },
  { value: "Accountancy", label: "Accountancy" }, { value: "E-Commerce", label: "E-Commerce" },
  { value: "Healthcare", label: "Healthcare" }, { value: "ProfessionalServices", label: "Professional Services" },
  { value: "Manufacturing", label: "Manufacturing" }, { value: "Logistics", label: "Logistics" },
  { value: "Finance", label: "Finance & Banking" }, { value: "Education", label: "Education" },
  { value: "Hospitality", label: "Hospitality" }, { value: "RealEstate", label: "Real Estate" },
];

const ALL_MODELS: { value: BusinessModel; label: string }[] = [
  { value: "SaaS", label: "SaaS" }, { value: "E-Commerce", label: "E-Commerce" },
  { value: "ProfessionalServices", label: "Professional Services" }, { value: "Construction", label: "Construction" },
  { value: "Manufacturing", label: "Manufacturing" }, { value: "Retail", label: "Retail" },
  { value: "Healthcare", label: "Healthcare" }, { value: "Education", label: "Education" },
];

const PHASES = [
  { id: "dna", label: "Company DNA" },
  { id: "map", label: "Business Map" },
  { id: "generate", label: "SOP Factory" },
];

function downloadPackage(sops: BatchSOP[], companyName: string) {
  function escapeHtml(s: string): string {
    return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
  }
  const bodiesHtml = sops.map(s => {
    const sectionsHtml = s.content.map(sec => {
      const linesHtml = sec.content.map(line => {
        const t = line.trim();
        if (/^Step \d+/.test(t)) return `<div class="step-box"><strong>${escapeHtml(t)}</strong></div>`;
        return `<p class="body-text">${escapeHtml(t)}</p>`;
      }).join("\n");
      return `<div class="section"><h2 class="section-heading">${escapeHtml(sec.heading)}</h2>${linesHtml}</div>`;
    }).join("\n");
    return `<div style="page-break-after:always;margin-bottom:24pt">
      <div class="doc-header">
        <div class="classification">Operational Document</div>
        <h1>${escapeHtml(s.title)}</h1>
        <p class="subtitle">${escapeHtml(companyName)} &mdash; ${escapeHtml(s.department)}</p>
      </div>
      <table class="meta-table">
        <tr><td class="label-cell">Document ID</td><td class="value-cell">${escapeHtml(s.id)}</td><td class="label-cell">Department</td><td class="value-cell">${escapeHtml(s.department)}</td></tr>
        <tr><td class="label-cell">Company</td><td class="value-cell">${escapeHtml(companyName)}</td><td class="label-cell">Industry</td><td class="value-cell">${escapeHtml(s.industry)}</td></tr>
      </table>
      ${sectionsHtml}
      <div class="footer"><p><strong>${escapeHtml(companyName)}</strong> &mdash; Standard Operating Procedure</p><p>Generated by SOPMaster &mdash; Confidential</p></div>
    </div>`;
  }).join("");
  const html = `<!DOCTYPE html>
<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
<head><meta charset="utf-8"><title>Batch SOP Package - ${escapeHtml(companyName)}</title>
<style>
  @page { margin: 0.8in 0.7in; }
  body { font-family:'Calibri','Arial',sans-serif; color:#1e293b; line-height:1.5; font-size:10.5pt; max-width:7.5in; margin:0 auto; }
  .doc-header { text-align:center; margin-bottom:18pt; padding-bottom:10pt; border-bottom:3px solid #0f172a; }
  .doc-header .classification { display:inline-block; font-size:7.5pt; font-weight:700; color:#fff; background:#0f172a; padding:3pt 12pt; margin-bottom:8pt; text-transform:uppercase; letter-spacing:2pt; }
  .doc-header h1 { font-size:18pt; font-weight:700; color:#0f172a; margin:0 0 4pt 0; }
  .doc-header .subtitle { font-size:10pt; color:#64748b; }
  .meta-table { width:100%; border-collapse:collapse; margin:10pt 0 16pt 0; border:1px solid #e2e8f0; }
  .meta-table td { padding:4pt 8pt; font-size:9pt; border:1px solid #e2e8f0; }
  .meta-table td.label-cell { font-weight:600; color:#0f172a; width:20%; background:#f8fafc; }
  .section { margin-bottom:14pt; }
  .section-heading { font-size:12pt; font-weight:700; color:#0f172a; margin:0 0 6pt 0; padding:6pt 10pt; background:#f8fafc; border-left:3px solid #0f172a; }
  .body-text { font-size:10.5pt; line-height:1.55; margin:3pt 0 8pt 0; color:#334155; }
  .step-box { padding:6pt 10pt; margin:4pt 0; background:#f8fafc; border-left:3px solid #0f172a; border-radius:2pt; }
  .footer { font-size:8pt; color:#94a3b8; margin-top:20pt; padding-top:8pt; border-top:1px solid #e2e8f0; text-align:center; }
  @media print { .section { break-inside: avoid; } }
</style></head>
<body>${bodiesHtml}</body></html>`;
  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = window.document.createElement("a");
  a.href = url; a.download = `SOP_Batch_${companyName.replace(/[^a-zA-Z0-9]/g, "_")}_${new Date().toISOString().slice(0, 10)}.html`; a.click();
  URL.revokeObjectURL(url);
}

export default function BatchPage() {
  const session = useStore((s) => s.session);
  const getCompany = useStore((s) => s.getCompany);
  const deductCredit = useStore((s) => s.deductCredit);
  const addNotification = useStore((s) => s.addNotification);
  const companyProfile = useStore((s) => s.companyProfile);
  const router = useRouter();
  const company = getCompany();

  const [phase, setPhase] = useState<"dna" | "map" | "generate">("dna");
  const [generating, setGenerating] = useState(false);
  const [logs, setLogs] = useState<string[]>([]);
  const [result, setResult] = useState<{ sops: BatchSOP[]; totalCount: number; departmentCounts: Record<string, number> } | null>(null);
  const [progress, setProgress] = useState(0);
  const [error, setError] = useState("");

  const [companyName, setCompanyName] = useState(company?.name || "");
  const [industry, setIndustry] = useState<Industry>((companyProfile?.industry as Industry) || "ProfessionalServices");
  const [jurisdiction, setJurisdiction] = useState<string>(company?.jurisdiction || "UK");
  const [companySize, setCompanySize] = useState(companyProfile?.companySize || "10");
  const [businessModel, setBusinessModel] = useState<BusinessModel>("ProfessionalServices");
  const [softwareInput, setSoftwareInput] = useState("");
  const [softwareStack, setSoftwareStack] = useState<string[]>(companyProfile?.softwareStack || []);
  const [businessGoals, setBusinessGoals] = useState(companyProfile?.businessGoals || "");
  const [operationalChallenges, setOperationalChallenges] = useState(companyProfile?.operationalChallenges || "");
  const [selectedDepartments, setSelectedDepartments] = useState<Department[]>(companyProfile?.departments || []);
  const [riskAppetite, setRiskAppetite] = useState("Medium");
  const [brandTone, setBrandTone] = useState("Professional");
  const [complianceReqs, setComplianceReqs] = useState("");

  useEffect(() => {
    if (company) { setCompanyName(company.name); setJurisdiction(company.jurisdiction); }
    if (companyProfile?.industry) setIndustry(companyProfile.industry as Industry);
    if (companyProfile?.companySize) setCompanySize(companyProfile.companySize);
    if (companyProfile?.departments && companyProfile.departments.length > 0) setSelectedDepartments(companyProfile.departments);
    if (companyProfile?.softwareStack) setSoftwareStack(companyProfile.softwareStack);
  }, [company, companyProfile]);

  useEffect(() => {
    router.prefetch("/armory");
  }, [router]);

  useEffect(() => {
    if (!session?.isDirector) router.push("/");
  }, [session, router]);

  const toggleDept = (d: Department) => { setSelectedDepartments(prev => prev.includes(d) ? prev.filter(x => x !== d) : [...prev, d]); };
  const addSoftware = (s: string) => { if (s.trim() && !softwareStack.includes(s.trim())) setSoftwareStack([...softwareStack, s.trim()]); setSoftwareInput(""); };
  const removeSoftware = (s: string) => setSoftwareStack(softwareStack.filter(x => x !== s));

  const nextPhase = () => {
    if (phase === "dna") {
      if (!companyName.trim()) { setError("Company name is required"); return; }
      setError(""); setPhase("map");
    } else if (phase === "map") {
      if (selectedDepartments.length === 0) { setError("Select at least one department"); return; }
      setError(""); setPhase("generate"); handleGenerate();
    }
  };

  const prevPhase = () => {
    if (phase === "map") setPhase("dna");
  };

  const handleGenerate = async () => {
    const batchCost = selectedDepartments.length * 30;
    if (!session?.isDirector) {
      const comp = getCompany();
      if (!comp || comp.credits < batchCost) { setError(`Insufficient credits. Batch costs ${batchCost} credits (30/dept).`); return; }
    }
    setGenerating(true); setProgress(0); setLogs([]); setResult(null);
    setLogs(l => [...l, "Generating batch documents across selected departments..."]);
    let batchResult: any;

    try {
      batchResult = await api.generate.batch({
        companyName: companyName.trim(), industry, jurisdiction, companySize, businessModel,
        softwareStack: softwareStack.length > 0 ? softwareStack : ["internal system"],
        departments: selectedDepartments, format: "json",
        riskAppetite, brandTone, complianceReqs, creditCost: batchCost,
      });
    } catch {
      batchResult = generateBatchPackage({
        companyName: companyName.trim(), industry, companySize, businessModel,
        softwareStack: softwareStack.length > 0 ? softwareStack : ["internal system"],
        businessGoals, operationalChallenges, departments: selectedDepartments,
      });
      await deductCredit(batchCost);
    }

    setProgress(100);
    setResult(batchResult);
    setLogs(l => [...l, `Package complete: ${batchResult.totalCount} SOPs across ${selectedDepartments.length} departments`]);
    setGenerating(false);
    addNotification({ type: "sop_generated", title: "Batch SOPs Generated", message: `${batchResult.totalCount} SOPs generated across ${selectedDepartments.length} departments for ${industry}.` });
  };

  if (!session || !company) return (
    <div className="splash-screen">
      <div className="splash-card">
        <div className="splash-logo">S</div>
        <div className="splash-spinner"></div>
        <p className="splash-text">Loading workspace...</p>
      </div>
    </div>
  );

  const isHalfPackage = selectedDepartments.length <= 7;

  return (
    <div style={{ maxWidth: "1120px", margin: "0 auto", padding: "40px 32px" }} className="fade-in">

      <div style={{ marginBottom: result ? "28px" : "24px" }}>
        <h1 style={{ fontSize: "28px", fontWeight: 600, color: "var(--text-primary)", marginBottom: "8px", letterSpacing: "-0.02em" }}>
          Batch Builder
        </h1>
        <p style={{ fontSize: "15px", color: "var(--text-secondary)" }}>
          Generate a complete Operational Infrastructure Package across multiple departments. 30 credits per department.
        </p>
      </div>

      {error && <div className="card" style={{ marginBottom: "16px", padding: "12px 16px", borderColor: "#EF4444" }}><p style={{ fontSize: "13px", color: "#EF4444" }}>{error}</p></div>}

      {/* Phase Stepper */}
      {!result && !generating && (
        <div style={{ display: "flex", gap: "10px", marginBottom: "28px", padding: "4px 0" }}>
          {PHASES.map((p, i) => (
            <div key={p.id} style={{
              display: "flex", alignItems: "center", gap: "10px", padding: "10px 18px",
              borderRadius: "10px", fontSize: "13px", fontWeight: 500, whiteSpace: "nowrap",
              background: phase === p.id ? "var(--accent-subtle)" : "var(--bg-card)",
              border: phase === p.id ? "1px solid rgba(37, 99, 235, 0.3)" : "1px solid var(--border)",
              color: phase === p.id ? "var(--accent)" : "var(--text-tertiary)",
              transition: "all 0.2s",
            }}>
              <span style={{
                width: "24px", height: "24px", borderRadius: "50%", display: "flex",
                alignItems: "center", justifyContent: "center", fontSize: "11px", fontWeight: 600,
                background: phase === p.id ? "var(--accent)" : "var(--bg-secondary)",
                color: phase === p.id ? "#fff" : "var(--text-tertiary)",
              }}>{i + 1}</span>
              {p.label}
            </div>
          ))}
        </div>
      )}

      {/* Phase 1 — Company DNA */}
      {phase === "dna" && !result && !generating && (
        <div>
          <div className="card" style={{ marginBottom: "24px", borderLeft: "3px solid var(--accent)" }}>
            <div className="card-header" style={{ fontSize: "14px", marginBottom: "20px" }}>
              Company DNA
            </div>
            <p style={{ fontSize: "14px", color: "var(--text-tertiary)", marginTop: "-12px", marginBottom: "24px" }}>
              Define your company&apos;s operating DNA. Every SOP in the package inherits these settings.
            </p>
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "16px" }}>
              <div>
                <label>Company Name</label>
                <input type="text" value={companyName} onChange={e => setCompanyName(e.target.value)} placeholder="Your company" />
              </div>
              <div>
                <label>Industry</label>
                <select value={industry} onChange={e => setIndustry(e.target.value as Industry)}>
                  {ALL_INDUSTRIES.map(i => <option key={i.value} value={i.value}>{i.label}</option>)}
                </select>
              </div>
              <div>
                <label>Jurisdiction</label>
                <select value={jurisdiction} onChange={e => setJurisdiction(e.target.value)}>
                  {Object.entries(JURISDICTION_REGULATORY).map(([key, val]) => <option key={key} value={key}>{val.name}</option>)}
                </select>
              </div>
              <div>
                <label>Business Model</label>
                <select value={businessModel} onChange={e => setBusinessModel(e.target.value as BusinessModel)}>
                  {ALL_MODELS.map(m => <option key={m.value} value={m.value}>{m.label}</option>)}
                </select>
              </div>
              <div>
                <label>Company Size (employees)</label>
                <input type="number" value={companySize} onChange={e => setCompanySize(e.target.value)} placeholder="e.g., 25" />
              </div>
              <div>
                <label>Risk Appetite</label>
                <select value={riskAppetite} onChange={e => setRiskAppetite(e.target.value)}>
                  <option value="Low">Low — Conservative</option>
                  <option value="Medium">Medium — Balanced</option>
                  <option value="High">High — Growth-focused</option>
                </select>
              </div>
              <div>
                <label>Brand Tone</label>
                <input type="text" value={brandTone} onChange={e => setBrandTone(e.target.value)} placeholder="e.g., Professional, Technical" />
              </div>
              <div>
                <label>Compliance Framework</label>
                <input type="text" value={complianceReqs} onChange={e => setComplianceReqs(e.target.value)} placeholder="e.g., ISO 9001, GDPR, SOX" />
              </div>
            </div>
            <div style={{ marginTop: "16px" }}>
              <label>Software Stack</label>
              <div style={{ display: "flex", flexWrap: "wrap", gap: "4px", marginBottom: "8px" }}>
                {softwareStack.map(s => (
                  <span key={s} className="tag tag-blue" style={{ cursor: "pointer" }} onClick={() => removeSoftware(s)}>{s} &times;</span>
                ))}
              </div>
              <input type="text" value={softwareInput} onChange={e => setSoftwareInput(e.target.value)}
                onKeyDown={e => { if (e.key === "Enter") addSoftware(softwareInput); }} placeholder="Type and press Enter" />
            </div>
            <div style={{ marginTop: "16px" }}>
              <label>Business Goals</label>
              <textarea value={businessGoals} onChange={e => setBusinessGoals(e.target.value)} placeholder="e.g., Scale operations, improve compliance, reduce manual work" rows={2} />
            </div>
          </div>
          <div style={{ display: "flex", justifyContent: "flex-end" }}>
            <button onClick={nextPhase} className="btn btn-primary" style={{ padding: "10px 32px", fontSize: "14px" }}>
              Next — Business Map →
            </button>
          </div>
        </div>
      )}

      {/* Phase 2 — Business Map */}
      {phase === "map" && !result && !generating && (
        <div>
          <div className="card" style={{ marginBottom: "24px", borderLeft: "3px solid var(--success)" }}>
            <div className="card-header" style={{ fontSize: "14px", marginBottom: "20px" }}>
              Business Map
            </div>
            <p style={{ fontSize: "14px", color: "var(--text-tertiary)", marginTop: "-12px", marginBottom: "24px" }}>
              Select the departments and processes to include. The SOP Factory will generate complete documentation for each.
            </p>
            <div style={{ marginBottom: "16px" }}>
              <label>Departments</label>
              <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))", gap: "4px", marginTop: "8px" }}>
                {ALL_DEPARTMENTS.map(d => (
                  <button key={d} onClick={() => toggleDept(d)}
                    style={{
                      textAlign: "left", padding: "8px 12px", fontSize: "13px", borderRadius: "6px", cursor: "pointer",
                      background: selectedDepartments.includes(d) ? "rgba(59,130,246,0.08)" : "transparent",
                      border: selectedDepartments.includes(d) ? "1px solid rgba(59,130,246,0.3)" : "1px solid #334155",
                      color: selectedDepartments.includes(d) ? "#F1F5F9" : "#94A3B8",
                    }}>
                    {d}
                  </button>
                ))}
              </div>
            </div>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "12px 0", borderTop: "1px solid #1E293B", marginTop: "8px" }}>
              <span style={{ fontSize: "12px", color: "#64748B" }}>{selectedDepartments.length} of {ALL_DEPARTMENTS.length} selected</span>
              <span style={{ fontSize: "12px", color: "#64748B" }}>
                Cost: {selectedDepartments.length * 30} credits (30/dept)
              </span>
            </div>
          </div>

          {/* Process Priority Preview */}
          {selectedDepartments.length > 0 && (
            <div className="card" style={{ marginBottom: "20px", padding: "16px 20px" }}>
              <p style={{ fontSize: "11px", fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.04em", color: "#64748B", marginBottom: "12px" }}>
                Process Priority Scoring
              </p>
              <p style={{ fontSize: "12px", color: "#94A3B8", marginBottom: "12px" }}>
                The SOP Factory scores every process by criticality, risk, revenue impact, and compliance need. Highest priority processes generate first.
              </p>
              <div style={{ display: "flex", gap: "16px", flexWrap: "wrap" }}>
                {["Business Criticality", "Risk", "Revenue Impact", "Compliance Impact", "Automation Potential"].map(label => (
                  <div key={label} style={{ display: "flex", alignItems: "center", gap: "6px" }}>
                    <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "#3B82F6" }} />
                    <span style={{ fontSize: "11px", color: "#94A3B8" }}>{label}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          <div style={{ display: "flex", justifyContent: "space-between" }}>
            <button onClick={prevPhase} className="btn btn-secondary" style={{ padding: "10px 24px", fontSize: "14px" }}>← Back</button>
            <div style={{ display: "flex", gap: "12px" }}>
              {selectedDepartments.length > 0 && (
                <span style={{ fontSize: "12px", color: "#64748B", alignSelf: "center" }}>
                  Est. {isHalfPackage ? "~3 min" : "~5 min"} &middot; {isHalfPackage ? `~${selectedDepartments.length * 5}` : `~${selectedDepartments.length * 4}`} SOPs
                </span>
              )}
              <button onClick={nextPhase} className="btn btn-primary" style={{ padding: "10px 32px", fontSize: "14px" }}>
                Generate Infrastructure Package →
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Loading — SOP Factory */}
      {generating && (
        <div className="card" style={{ maxWidth: "560px", margin: "0 auto", textAlign: "center", padding: "48px 32px" }}>
          <div style={{ marginBottom: "16px" }}>
            <span style={{ fontSize: "11px", fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.08em", color: "#22C55E" }}>
              BATCH BUILDER v3.0 — Running 8-Phase Factory
            </span>
          </div>
          <h2 style={{ fontSize: "16px", fontWeight: 600, color: "#F1F5F9", marginBottom: "4px" }}>Generating Operational Infrastructure</h2>
          <p style={{ fontSize: "13px", color: "#64748B", marginBottom: "24px" }}>
            {selectedDepartments.length} departments &middot; ~{isHalfPackage ? "3" : "5"} minutes
          </p>
          <div className="progress-bar" style={{ marginBottom: "12px", height: "8px" }}>
            <div className="progress-fill" style={{ width: `${progress}%`, height: "8px" }} />
          </div>
          <p style={{ fontSize: "12px", color: "#22C55E", fontWeight: 500, marginBottom: "20px" }}>{Math.round(progress)}%</p>
          <div style={{
            textAlign: "left", padding: "12px 16px", background: "rgba(0,0,0,0.3)", borderRadius: "8px",
            maxHeight: "240px", overflowY: "auto", fontFamily: "monospace", fontSize: "12px",
          }}>
            {logs.map((log, i) => (
              <p key={i} style={{
                color: log === "Complete" ? "#22C55E" : "#94A3B8",
                marginBottom: "6px", display: "flex", alignItems: "center", gap: "8px",
              }}>
                <span style={{ color: "#475569" }}>{String(i + 1).padStart(2, "0")}</span>
                {log}
              </p>
            ))}
          </div>
        </div>
      )}

      {/* Results — Operational Infrastructure Package */}
      {result && !generating && (
        <div className="fade-in">
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "16px", flexWrap: "wrap", gap: "8px" }}>
            <div>
              <span style={{ fontSize: "13px", color: "#22C55E", fontWeight: 500 }}>✓ Operational Infrastructure Package complete</span>
              <span style={{ fontSize: "11px", color: "#64748B", marginLeft: "12px" }}>
                {result.totalCount} SOPs &middot; {selectedDepartments.length} departments &middot; Cross-linked &middot; Quality verified
              </span>
            </div>
            <div style={{ display: "flex", gap: "8px" }}>
              <button onClick={() => downloadPackage(result.sops, companyName)} className="btn btn-secondary" style={{ fontSize: "12px" }}>
                Download Package (HTML)
              </button>
              <button onClick={() => { setResult(null); setLogs([]); setProgress(0); setPhase("dna"); }} className="btn btn-primary" style={{ fontSize: "12px" }}>
                New Batch
              </button>
            </div>
          </div>

          {/* Summary Cards */}
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))", gap: "12px", marginBottom: "20px" }}>
            <div className="card" style={{ padding: "16px", textAlign: "center" }}>
              <div className="stat-label">Total SOPs</div>
              <div className="stat-value" style={{ color: "#3B82F6", fontSize: "28px" }}>{result.totalCount}</div>
            </div>
            <div className="card" style={{ padding: "16px", textAlign: "center" }}>
              <div className="stat-label">Departments</div>
              <div className="stat-value">{selectedDepartments.length}</div>
            </div>
            <div className="card" style={{ padding: "16px", textAlign: "center" }}>
              <div className="stat-label">Industry</div>
              <div className="stat-value" style={{ fontSize: "14px" }}>{industry}</div>
            </div>
            <div className="card" style={{ padding: "16px", textAlign: "center" }}>
              <div className="stat-label">Company</div>
              <div className="stat-value" style={{ fontSize: "14px" }}>{companyName}</div>
            </div>
          </div>

          {/* Department Breakdown */}
          <div className="card" style={{ padding: "20px" }}>
            <div className="card-header" style={{ fontSize: "13px", marginBottom: "16px" }}>
              Department Breakdown
            </div>
            {Object.entries(result.departmentCounts).map(([dept, count]) => (
              <div key={dept} style={{ marginBottom: "16px" }}>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "8px" }}>
                  <span style={{ fontSize: "12px", fontWeight: 600, color: "#F1F5F9" }}>{dept}</span>
                  <span style={{ fontSize: "11px", color: "#64748B" }}>{count} SOPs</span>
                </div>
                <div style={{ display: "flex", flexDirection: "column", gap: "4px" }}>
                  {result.sops.filter(s => s.department === dept).map((sop, idx) => (
                    <div key={sop.id} style={{
                      display: "flex", justifyContent: "space-between", alignItems: "center",
                      padding: "6px 10px", background: "rgba(0,0,0,0.15)", borderRadius: "4px",
                    }}>
                      <span style={{ fontSize: "12px", color: "#94A3B8" }}>{idx + 1}. {sop.title}</span>
                      <span style={{ fontSize: "10px", color: "#475569", fontFamily: "monospace" }}>{sop.id}</span>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
