"use client";

import { useState } from "react";
import { useStore } from "@/lib/store";
import { generateSOPDocument } from "@/lib/sop-generator";
import { buildSopHtml } from "@/lib/utils";
import { useRouter } from "next/navigation";

function downloadHtml(sop: import("@/types").SOP) {
  const doc = generateSOPDocument(
    sop.title, sop.company, sop.systems, sop.headcount,
    sop.jurisdiction, sop.complexity, sop.industry || "ProfessionalServices", sop.sopType || "Operational"
  );
  const html = buildSopHtml(
    doc.title, doc.company, doc.jurisdiction, sop.id, sop.verificationHash,
    doc.industry, doc.complexity, doc.sopType, sop.dateCreated, sop.createdBy, sop.version,
    doc.sections
  );
  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = window.document.createElement("a");
  a.href = url; a.download = `${sop.title.replace(/[^a-zA-Z0-9]/g, "_")}.html`; a.click();
  URL.revokeObjectURL(url);
}

function downloadZip(sops: import("@/types").SOP[]) {
  const bodiesHtml = sops.map(s => {
    const doc = generateSOPDocument(
      s.title, s.company, s.systems, s.headcount,
      s.jurisdiction, s.complexity, s.industry || "ProfessionalServices", s.sopType || "Operational"
    );
    const sectionsHtml = doc.sections.map(sec => `
      <div style="margin-bottom:16pt">
        <h2 style="font-size:13pt;font-weight:700;color:#1a1a2e;margin:0 0 6pt 0;padding-bottom:4pt;border-bottom:2px solid #1a1a2e">${sec.heading}</h2>
        ${sec.content.map(line => `<p style="font-size:11pt;line-height:1.5;margin:2pt 0;color:#333">${line}</p>`).join("")}
      </div>`).join("");
    return `<div style="page-break-after:always;margin-bottom:24pt">
      <div style="text-align:center;margin-bottom:24pt;padding-bottom:12pt;border-bottom:3px solid #1a1a2e">
        <div style="display:inline-block;font-size:9pt;font-weight:700;color:#fff;background:#1a1a2e;padding:3pt 12pt;margin-bottom:8pt;text-transform:uppercase;letter-spacing:2pt">Controlled Document</div>
        <h1 style="font-size:20pt;font-weight:700;color:#1a1a2e;margin:0 0 4pt 0;text-transform:uppercase;letter-spacing:1pt">${s.title}</h1>
        <p style="font-size:11pt;color:#555;margin:4pt 0">${s.company} &mdash; ${s.industry || "General"} &mdash; ${s.jurisdiction}</p>
      </div>
      <table style="width:100%;border-collapse:collapse;margin:12pt 0 18pt 0">
        <tr><td style="padding:4pt 8pt;font-size:10pt;border:1px solid #ccc;font-weight:600;color:#1a1a2e;width:20%;background:#f5f5f5">Document ID</td><td style="padding:4pt 8pt;font-size:10pt;border:1px solid #ccc;color:#333">${s.id}</td>
          <td style="padding:4pt 8pt;font-size:10pt;border:1px solid #ccc;font-weight:600;color:#1a1a2e;width:15%;background:#f5f5f5">Version</td><td style="padding:4pt 8pt;font-size:10pt;border:1px solid #ccc;color:#333">${s.version}.0</td></tr>
        <tr><td style="padding:4pt 8pt;font-size:10pt;border:1px solid #ccc;font-weight:600;color:#1a1a2e;background:#f5f5f5">Jurisdiction</td><td style="padding:4pt 8pt;font-size:10pt;border:1px solid #ccc;color:#333">${s.jurisdiction}</td>
          <td style="padding:4pt 8pt;font-size:10pt;border:1px solid #ccc;font-weight:600;color:#1a1a2e;background:#f5f5f5">Status</td><td style="padding:4pt 8pt;font-size:10pt;border:1px solid #ccc;color:#333">Active</td></tr>
        <tr><td style="padding:4pt 8pt;font-size:10pt;border:1px solid #ccc;font-weight:600;color:#1a1a2e;background:#f5f5f5">Effective</td><td style="padding:4pt 8pt;font-size:10pt;border:1px solid #ccc;color:#333">${s.dateCreated}</td>
          <td style="padding:4pt 8pt;font-size:10pt;border:1px solid #ccc;font-weight:600;color:#1a1a2e;background:#f5f5f5">Owner</td><td style="padding:4pt 8pt;font-size:10pt;border:1px solid #ccc;color:#333">${s.createdBy}</td></tr>
      </table>
      ${sectionsHtml}
      <div style="font-size:9pt;color:#888;margin-top:24pt;border-top:1px solid #ccc;padding-top:8pt;text-align:center">
        <p style="margin:1pt 0"><strong>${s.company}</strong> &mdash; Standard Operating Procedure</p>
        <p style="margin:1pt 0">Generated by SOPMaster &mdash; Confidential &mdash; Not for external distribution</p>
      </div>
    </div>`;
  }).join("");
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>SOP Batch Export</title></head><body style="font-family:'Calibri','Arial',sans-serif;color:#222;line-height:1.4">${bodiesHtml}</body></html>`;
  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = window.document.createElement("a");
  a.href = url; a.download = `SOP_Export_${new Date().toISOString().slice(0, 10)}.html`; a.click();
  URL.revokeObjectURL(url);
}

export default function ArmoryPage() {
  const session = useStore((s) => s.session);
  const vault = useStore((s) => s.vault);
  const getCompany = useStore((s) => s.getCompany);
  const updateSOP = useStore((s) => s.updateSOP);
  const removeSOP = useStore((s) => s.removeSOP);
  const router = useRouter();
  const [viewingSop, setViewingSop] = useState<string | null>(null);
  const [search, setSearch] = useState("");
  const [filterStatus, setFilterStatus] = useState<"all" | "active" | "archived">("all");
  const [filterFav, setFilterFav] = useState(false);

  const company = getCompany();

  const handleRemove = (sopId: string) => {
    removeSOP(sopId);
    if (viewingSop === sopId) setViewingSop(null);
  };

  const handleToggleArchive = (sopId: string, currentStatus: string) => {
    const newStatus = currentStatus === "archived" ? "active" : "archived";
    updateSOP(sopId, { status: newStatus });
  };

  const handleToggleFavorite = (sopId: string, currentFavorite: boolean) => {
    updateSOP(sopId, { favorite: !currentFavorite });
  };

  let filtered = vault.filter(s => {
    const matchesSearch = s.title.toLowerCase().includes(search.toLowerCase()) || s.company.toLowerCase().includes(search.toLowerCase()) || s.hash.includes(search) || (s.department || "").toLowerCase().includes(search.toLowerCase());
    const matchesStatus = filterStatus === "all" || s.status === filterStatus;
    const matchesFav = !filterFav || s.favorite;
    return matchesSearch && matchesStatus && matchesFav;
  });

  if (!session || !company) return null;
  const selectedSop = viewingSop ? vault.find(s => s.id === viewingSop) : null;

  return (
    <div style={{ maxWidth: "1120px", margin: "0 auto", padding: "48px 24px" }} className="fade-in">
      <div style={{ marginBottom: "28px" }}>
        <h1 style={{ fontSize: "28px", fontWeight: 600, color: "#F8FAFC", marginBottom: "8px", letterSpacing: "-0.02em" }}>
          Document Vault
        </h1>
        <p style={{ fontSize: "15px", color: "#94A3B8" }}>
          {vault.filter(s => s.status === "active").length} active documents &middot; {vault.filter(s => s.favorite).length} starred
        </p>
      </div>

      {!viewingSop ? (
        <>
          <div style={{ display: "flex", gap: "12px", marginBottom: "20px", flexWrap: "wrap", alignItems: "center" }}>
            <input type="text" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search by title, company, or hash..." style={{ flex: 1, minWidth: "200px", background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.06)" }} />
            <select value={filterStatus} onChange={e => setFilterStatus(e.target.value as "all" | "active" | "archived")} style={{ width: "auto", minWidth: "130px", background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.06)" }}>
              <option value="all">All documents</option>
              <option value="active">Active</option>
              <option value="archived">Archived</option>
            </select>
            <button onClick={() => setFilterFav(!filterFav)} className={filterFav ? "btn btn-primary" : "btn btn-secondary"} style={{ fontSize: "12px" }}>
              {filterFav ? "\u2605 Starred" : "\u2606 Starred"}
            </button>
          </div>

          {filtered.length === 0 ? (
            <div className="card" style={{ textAlign: "center", padding: "56px 36px" }}>
              <p style={{ fontSize: "15px", color: "#94A3B8", marginBottom: "20px" }}>
                {search ? "No documents match your search." : "No documents in the vault yet."}
              </p>
              <button onClick={() => router.push("/forge")} className="btn btn-primary" style={{ padding: "12px 32px" }}>
                Generate Document
              </button>
            </div>
          ) : (
            <>
              <div className="card mobile-safe-overflow" style={{ padding: 0 }}>
                <div className="doc-row-header" style={{ display: "flex", padding: "10px 20px", borderBottom: "1px solid rgba(255,255,255,0.04)", fontSize: "11px", fontWeight: 600, color: "#64748B", textTransform: "uppercase", letterSpacing: "0.06em" }}>
                  <span style={{ flex: "1 1 30%", minWidth: "100px" }}>Title</span>
                  <span className="hide-mobile" style={{ flex: "0 0 90px" }}>Jurisdiction</span>
                  <span className="hide-mobile" style={{ flex: "0 0 60px", textAlign: "center" }}>Ver.</span>
                  <span style={{ flex: "0 0 70px", textAlign: "center" }}>Status</span>
                  <span className="hide-mobile" style={{ flex: "0 0 90px", textAlign: "right" }}>Date</span>
                  <span style={{ flex: "0 0 80px", textAlign: "right" }}>Actions</span>
                </div>
                {filtered.map((sop) => (
                  <div key={sop.id} className="doc-row" style={{ flexWrap: "nowrap", gap: "4px" }}>
                    <span style={{ flex: "1 1 30%", minWidth: "80px", fontWeight: 500, color: "#F1F5F9", cursor: "pointer", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}
                      onClick={() => setViewingSop(sop.id)}>
                      {sop.favorite && <span style={{ color: "#F59E0B", marginRight: "2px" }}>&#9733;</span>}
                      {sop.title}
                    </span>
                    <span className="hide-mobile" style={{ flex: "0 0 90px", fontSize: "11px" }}>
                      <span className="tag tag-blue" style={{ fontSize: "10px", padding: "1px 6px" }}>{sop.jurisdiction}</span>
                    </span>
                    <span className="hide-mobile" style={{ flex: "0 0 60px", textAlign: "center", fontSize: "11px", color: "#94A3B8" }}>v{sop.version}</span>
                    <span style={{ flex: "0 0 70px", textAlign: "center" }}>
                      <span className={`tag ${sop.status === "active" ? "tag-green" : ""}`} style={{ fontSize: "10px", padding: "1px 6px" }}>{sop.status}</span>
                    </span>
                    <span className="hide-mobile" style={{ flex: "0 0 90px", textAlign: "right", fontSize: "11px", color: "#64748B" }}>{sop.dateCreated}</span>
                    <span style={{ flex: "0 0 80px", textAlign: "right", display: "flex", gap: "2px", justifyContent: "flex-end" }}>
                      <button onClick={() => handleToggleFavorite(sop.id, sop.favorite!)} className="btn-ghost" style={{ fontSize: "11px", padding: "1px 4px", color: sop.favorite ? "#F59E0B" : "#64748B" }}>
                        {sop.favorite ? "\u2605" : "\u2606"}
                      </button>
                      <button onClick={() => downloadHtml(sop)} className="btn-ghost" style={{ fontSize: "10px", padding: "1px 4px" }} title="Download HTML" aria-label="Download">
                        &darr;
                      </button>
                      <button onClick={() => handleToggleArchive(sop.id, sop.status)} className="btn-ghost" style={{ fontSize: "10px", padding: "1px 4px" }} title={sop.status === "archived" ? "Restore" : "Archive"} aria-label={sop.status === "archived" ? "Restore" : "Archive"}>
                        {sop.status === "archived" ? "\u21A9" : "\uD83D\uDCC1"}
                      </button>
                      <button onClick={() => handleRemove(sop.id)} className="btn-ghost" style={{ fontSize: "11px", padding: "1px 4px", color: "#EF4444" }} title="Delete" aria-label="Delete">
                        &times;
                      </button>
                    </span>
                  </div>
                ))}
              </div>

              {filtered.length > 1 && (
                <div style={{ textAlign: "right", marginTop: "12px" }}>
                  <button onClick={() => downloadZip(filtered)} className="btn btn-secondary" style={{ fontSize: "12px" }}>
                    Download All (HTML)
                  </button>
                </div>
              )}
            </>
          )}
        </>
      ) : selectedSop ? (
        <div className="fade-in">
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "16px" }}>
            <button onClick={() => setViewingSop(null)} className="btn btn-secondary" style={{ fontSize: "12px" }}>&larr; Back</button>
            <div style={{ display: "flex", gap: "8px" }}>
              <button onClick={() => handleToggleFavorite(selectedSop.id, selectedSop.favorite!)} className="btn btn-secondary" style={{ fontSize: "12px" }}>
                {selectedSop.favorite ? "\u2605 Starred" : "\u2606 Star"}
              </button>
              <button onClick={() => handleToggleArchive(selectedSop.id, selectedSop.status)} className="btn btn-secondary" style={{ fontSize: "12px" }}>
                {selectedSop.status === "archived" ? "Restore" : "Archive"}
              </button>
              <button onClick={() => downloadHtml(selectedSop)} className="btn btn-primary" style={{ fontSize: "12px" }}>
                Download HTML
              </button>
            </div>
          </div>

            <div className="card" style={{ padding: "36px" }}>
            <div className="meta-grid" style={{ marginBottom: "24px", padding: "20px", background: "rgba(255,255,255,0.03)", borderRadius: "10px", border: "1px solid rgba(255,255,255,0.04)", display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(120px, 1fr))", gap: "12px" }}>
              <div><div className="stat-label">SOP ID</div><div style={{ fontSize: "13px", fontFamily: "monospace", color: "#F8FAFC", marginTop: "2px", wordBreak: "break-all" }}>{selectedSop.id}</div></div>
              <div><div className="stat-label">Version</div><div style={{ fontSize: "13px", color: "#F8FAFC", marginTop: "2px" }}>{selectedSop.version}.0</div></div>
              <div><div className="stat-label">Created</div><div style={{ fontSize: "13px", color: "#F8FAFC", marginTop: "2px" }}>{selectedSop.dateCreated}</div></div>
              <div><div className="stat-label">Owner</div><div style={{ fontSize: "13px", color: "#F8FAFC", marginTop: "2px" }}>{selectedSop.createdBy}</div></div>
              <div><div className="stat-label">Jurisdiction</div><div style={{ fontSize: "13px", color: "#3B82F6", marginTop: "2px" }}>{selectedSop.jurisdiction}</div></div>
            </div>

            {selectedSop.industry && (
              <div className="meta-grid" style={{ marginBottom: "24px", padding: "20px", background: "rgba(255,255,255,0.03)", borderRadius: "10px", border: "1px solid rgba(255,255,255,0.04)", display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(120px, 1fr))", gap: "12px" }}>
                <div><div className="stat-label">Industry</div><div style={{ fontSize: "13px", color: "#F8FAFC", marginTop: "2px" }}>{selectedSop.industry}</div></div>
                <div><div className="stat-label">Department</div><div style={{ fontSize: "13px", color: "#F8FAFC", marginTop: "2px" }}>{selectedSop.department || "\u2014"}</div></div>
                <div><div className="stat-label">Type</div><div style={{ fontSize: "13px", color: "#F8FAFC", marginTop: "2px" }}>{selectedSop.sopType || "Operational"}</div></div>
                <div><div className="stat-label">Status</div><div style={{ fontSize: "13px", color: selectedSop.status === "active" ? "#22C55E" : "#64748B", marginTop: "2px" }}>{selectedSop.status}</div></div>
              </div>
            )}

            <div style={{ marginBottom: "16px" }}>
              <h2 style={{ fontSize: "18px", fontWeight: 600, color: "#F1F5F9", marginBottom: "2px" }}>{selectedSop.title}</h2>
              <p style={{ fontSize: "13px", color: "#94A3B8" }}>{selectedSop.company} &middot; {selectedSop.complexity} &middot; {selectedSop.systems}</p>
            </div>

            <div style={{ marginBottom: "20px", padding: "12px 16px", background: "rgba(59,130,246,0.06)", borderRadius: "6px", border: "1px solid rgba(59,130,246,0.15)" }}>
              <p style={{ fontSize: "12px", color: "#3B82F6", fontWeight: 600, marginBottom: "4px", textTransform: "uppercase", letterSpacing: "0.04em" }}>Framework Context</p>
              <p style={{ fontSize: "13px", color: "#94A3B8" }}>
                This procedure integrates within the broader {selectedSop.company} management system.
              </p>
            </div>

            <div style={{ fontSize: "13px", color: "#64748B", marginBottom: "20px", fontFamily: "monospace" }}>
              Verification: {selectedSop.verificationHash}
            </div>
          </div>
        </div>
      ) : null}

      <style>{`
        @media (min-width: 769px) {
          .desktop-col { display: block !important; }
        }
      `}</style>
    </div>
  );
}
